// app.js - LoopDraft Draft Generation Engine
// Integrates Flywheel + Revenue for fully automated content generation.

function generateDraft() {
  const topic = (document.getElementById('topicInput').value || '').trim() || 'content strategy for indie founders';
  const output = document.getElementById('outputArea');
  output.innerHTML = '<em style="color:#9ca3af">Generating your draft...</em>';

  // Fire flywheel signal
  const profile = (typeof Flywheel !== 'undefined') ? Flywheel.onDraftGenerated(topic) : { draftCount: 1, proConversionSignal: false };

  // Get personalization context
  const ctx = (typeof Flywheel !== 'undefined') ? Flywheel.getPersonalizationContext() : { tone: 'balanced and direct', preferredStructures: [] };

  setTimeout(() => {
    const draft = buildDraft(topic, ctx);
    output.innerHTML = renderDraft(draft, topic);

    // Route revenue logic
    if (typeof Revenue !== 'undefined') Revenue.route(profile);
  }, 1100);
}

function buildDraft(topic, ctx) {
  const structures = ['TL;DR', '3 Biggest Mistakes', '5-Step Framework', 'Key Takeaways'];
  return {
    title: topic,
    tone: ctx.tone || 'balanced and direct',
    sections: [
      { type: 'tldr', content: 'This guide covers why ' + topic + ' matters in 2026 - the 3 biggest mistakes and a 5-step framework that compounds.' },
      { type: 'why', content: 'The teams winning in 2026 are not the ones with the biggest budgets - they are the ones with the clearest systems. ' + topic + ' is a force multiplier, not an afterthought.' },
      { type: 'mistakes', items: ['Skipping the research phase - jumping to execution without validating the core assumption.', 'Optimizing for volume over resonance - 10 targeted pieces outperform 100 generic ones.', 'No feedback loop - if you are not measuring what lands, you are publishing into the void.'] },
      { type: 'framework', items: ['Step 1 - Define your ICP signal.', 'Step 2 - Map the pain stack.', 'Step 3 - Draft the value bridge.', 'Step 4 - Write the hook first.', 'Step 5 - End with a next step.'] },
    ],
    structures,
  };
}

function renderDraft(draft, topic) {
  let html = '';
  html += '<div style="margin-bottom:.5rem">';
  html += '<span class="tag">Blog Post</span>';
  html += '<span class="tag">SEO Score: 84/100</span>';
  html += '<span class="tag">~4 min read</span>';
  html += '</div>';
  html += '<strong style="font-size:1rem;display:block;margin-bottom:.75rem">' + topic + '</strong>';

  draft.sections.forEach(section => {
    if (section.type === 'tldr') {
      html += '<strong>TL;DR:</strong> ' + section.content + '<br><br>';
    } else if (section.type === 'why') {
      html += '<strong>Why it matters now:</strong> ' + section.content + '<br><br>';
    } else if (section.type === 'mistakes') {
      html += '<strong>The 3 Biggest Mistakes</strong><br>';
      section.items.forEach((item, i) => { html += (i+1) + '. ' + item + '<br>'; });
      html += '<br>';
    } else if (section.type === 'framework') {
      html += '<strong>5-Step Framework</strong><br>';
      section.items.forEach(item => { html += item + '<br>'; });
      html += '<br>';
    }
  });

  html += '<em style="font-size:.8rem;color:#9ca3af">Generated by LoopDraft. Edit and publish in minutes.</em>';
  html += '<div style="display:flex;gap:.5rem;margin-top:.75rem">';
  html += '<button onclick="copyDraft()" style="background:#5c6ef8;color:#fff;border:none;padding:.4rem .9rem;border-radius:6px;font-size:.8rem;cursor:pointer">Copy Markdown</button>';
  html += '<button onclick="exportHTML()" style="background:#f3f4f6;border:none;padding:.4rem .9rem;border-radius:6px;font-size:.8rem;cursor:pointer">Export HTML</button>';
  html += '<button onclick="regenerate()" style="background:#f3f4f6;border:none;padding:.4rem .9rem;border-radius:6px;font-size:.8rem;cursor:pointer">Regenerate</button>';
  html += '</div>';
  return html;
}

function copyDraft() {
  if (typeof Flywheel !== 'undefined') Flywheel.onDraftKept(['TL;DR', '5-Step Framework'], 0.5);
  if (typeof Revenue !== 'undefined') {
    const content = document.getElementById('outputArea').innerText;
    const withLinks = Revenue.injectAffiliateLinks(content);
    navigator.clipboard.writeText(withLinks).then(() => alert('Copied to clipboard with LoopDraft attribution!')).catch(() => alert('Draft ready - select and copy manually.'));
  }
}

function exportHTML() {
  if (typeof Flywheel !== 'undefined') Flywheel.onPublish();
  const content = document.getElementById('outputArea').innerHTML;
  const blob = new Blob(['<!DOCTYPE html><html><body>' + content + '</body></html>'], {type: 'text/html'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'loopdraft-export.html';
  a.click();
}

function regenerate() {
  if (typeof Flywheel !== 'undefined') Flywheel.onRegenerate();
  generateDraft();
}
