// revenue.js - LoopDraft Revenue Optimization Engine
// Frictionless, zero-human-intervention revenue layer.
// Stripe Payment Link injected - no backend required.

const Revenue = (() => {

  const STRIPE = {
    pro_monthly: 'https://buy.stripe.com/test_cNi00lejKe1g6CV3oo2wU00',
    pro_annual:  'https://buy.stripe.com/test_cNi00lejKe1g6CV3oo2wU00',
  };

  const AFFILIATES = {
    groq:   { url: 'https://groq.com/?ref=loopdraft',   label: 'Groq API (free tier)' },
    vercel: { url: 'https://vercel.com/?ref=loopdraft', label: 'Vercel (free hosting)' },
    ghost:  { url: 'https://ghost.org/?ref=loopdraft',  label: 'Ghost (publish platform)' },
  };

  const injectAffiliateLinks = (markdownContent) => {
    const footer = [
      '',
      '---',
      '*Generated by [LoopDraft](https://loopdraft.io) - free AI content engine.*',
      '*Powered by [Groq](https://groq.com/?ref=loopdraft) + [Vercel](https://vercel.com/?ref=loopdraft)*',
    ].join('\n');
    return markdownContent + footer;
  };

  const showUpgradeModal = () => {
    if (document.getElementById('ld-upgrade-modal')) return;
    const modal = document.createElement('div');
    modal.id = 'ld-upgrade-modal';
    modal.style.cssText = 'position:fixed;inset:0;background:rgba(0,0,0,.5);z-index:1000;display:flex;align-items:center;justify-content:center';
    modal.innerHTML = '<div style="background:#fff;border-radius:16px;padding:2.5rem;max-width:440px;width:90%;text-align:center;box-shadow:0 20px 60px rgba(0,0,0,.2)">' +
      '<div style="font-size:2rem;margin-bottom:.5rem">🚀</div>' +
      '<h2 style="font-size:1.4rem;font-weight:800;margin-bottom:.5rem">You have used your 5 free drafts</h2>' +
      '<p style="color:#6b7280;margin-bottom:1.5rem">Upgrade to Pro for unlimited drafts, brand voice training, and one-click CMS publish. Just $9/month.</p>' +
      '<div style="display:grid;gap:.75rem">' +
      '<a href="' + STRIPE.pro_monthly + '" target="_blank" style="background:#5c6ef8;color:#fff;padding:.85rem 2rem;border-radius:12px;font-weight:700;text-decoration:none;display:block">Upgrade to Pro - $9/mo</a>' +
      '<a href="' + STRIPE.pro_annual + '" target="_blank" style="background:#ede9fe;color:#5b21b6;padding:.85rem 2rem;border-radius:12px;font-weight:700;text-decoration:none;display:block">Annual - $79/yr (save $29)</a>' +
      '<button onclick="document.getElementById(\"ld-upgrade-modal\").remove()" style="background:none;border:none;color:#9ca3af;cursor:pointer;font-size:.85rem;padding:.5rem">Maybe later</button>' +
      '</div>' +
      '<p style="font-size:.75rem;color:#9ca3af;margin-top:1rem">No contracts. Cancel anytime.</p>' +
      '</div>';
    document.body.appendChild(modal);
  };

  const showAffiliateOffer = () => {
    const toast = document.createElement('div');
    toast.style.cssText = 'position:fixed;bottom:1.5rem;right:1.5rem;background:#0f0f0f;color:#fff;border-radius:12px;padding:1.25rem 1.5rem;max-width:320px;z-index:999;box-shadow:0 8px 30px rgba(0,0,0,.3)';
    toast.innerHTML = '<div style="font-weight:700;margin-bottom:.3rem">Earn with LoopDraft</div>' +
      '<p style="font-size:.85rem;color:#9ca3af;margin-bottom:.75rem">You are a power user. Share your link and earn 30% recurring commission.</p>' +
      '<a href="https://loopdraft.io/affiliate" style="background:#5c6ef8;color:#fff;padding:.5rem 1rem;border-radius:8px;font-weight:700;font-size:.85rem;text-decoration:none;display:inline-block">Get your link</a>' +
      '<button onclick="this.parentElement.remove()" style="background:none;border:none;color:#6b7280;cursor:pointer;font-size:.8rem;margin-left:.75rem">Dismiss</button>';
    document.body.appendChild(toast);
  };

  const route = (profile) => {
    if (profile.proConversionSignal && !profile._proModalShown) {
      showUpgradeModal();
      profile._proModalShown = true;
    }
    if (profile.affiliateEligible && !profile._affiliateShown) {
      setTimeout(() => showAffiliateOffer(), 3000);
      profile._affiliateShown = true;
    }
  };

  return { injectAffiliateLinks, showUpgradeModal, showAffiliateOffer, route, AFFILIATES, STRIPE };
})();
